Update SqlReceiver.cs
A little patch to prevent an crash because of uncaught exception if the Messages_0_Id table is empty for any reason :

System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at Microsoft.AspNet.SignalR.SqlServer.SqlReceiver.Receive(Object state)

I think there is room for optimization, but this is just a suggestion.
After all, the table should never be empty.